name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

     
      - uses: actions/setup-node@v4
        with:
          node-version: 20

     
      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json', '**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install
        run: npm install

      - name: Compile
        run: npx hardhat compile

      - name: Lint
        run: npm run lint

      - name: Test
        run: npx hardhat test
